settings:
  digits: 3
  itemformat: yaml
  prefix: TUI
  sep: '_'
attributes:
  defaults:
    owned-by: sarnold
    doc:
      name: Requirements
      title: Requirements for _TUI_
      ref: ''
      by: sarnold
      major: '1'
      minor: A
      copyright: sarnold
  publish:
    - owned-by
