name: Containers

on:
  workflow_dispatch:
  #workflow_call:
  #pull_request:
  #push:
    #branches: [ master ]

jobs:
  extra_wheels:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:buster
          - debian:sid
          - centos:7
          - centos:8
          - rhel:8
          - rhel:9
          - fedora:latest
          - fedora:rawhide

    runs-on: ubuntu-22.04
    container:
      image: ${{ matrix.image }}

    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    env:
      PYTHONIOENCODING: utf-8
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache

    steps:
      #- name: Set git crlf/eol
        #run: |
          #git config --global core.autocrlf false
          #git config --global core.eol lf

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install tox

      - name: Build dist pkgs
        run: |
          tox -e build,check
