name: mermaid_diagrams

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: get changed files
        id: getfile
        run: |
          files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' | xargs)
          echo "Changed files: ${files}"
          echo "files=${files}" >> $GITHUB_OUTPUT

      - name: mermaid files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: Compile Mermaid in Markdown
        uses: divvun/compile-mermaid-markdown-action@v1.0.0
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'output'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: "svg"

      - name: show changes
        run: |
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e  # v7.0.8
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: cpr/updated-diagrams
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          base: master
          labels: |
            automerge
          sign-commits: true
          delete-branch: true
          title: '[MMDC] New mermaid files compiled.'
          body: |
            Update report
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
